### ISSUE TITLE
npm run dev output error sometimes

### ISSUE THREAD

**Issue by afc163** [ant-tool/atool-build#130]
```
webpack: bundle build is now finished.
webpack built 58ba0da54f54a5d27171 in 1239ms

  Error: write EPIPE
      at Object.exports._errnoException (util.js:856:11)
      at exports._exceptionWithHostPort (util.js:879:20)
      at WriteWrap.afterWrite (net.js:763:14)

webpack building...
```

**Comment by afc163** [comment]
Another error:

```
  Error: read ECONNRESET
      at exports._errnoException (util.js:856:11)
      at TCP.onread (net.js:544:26)
```

**Comment by sorrycc** [comment]
没遇到过，怎么重现呢 ?

**Comment by afc163** [comment]
不知道，偶尔会出现，可以试试 ant-design 的 develop-1.0.0 分支。

**Comment by jljsj33** [comment]
我那出现四个，，求救。。。。
