### ISSUE TITLE
使用的是其他脚手架定制主题时，报is not a PostCSS plugin错误。

### ISSUE THREAD

**Issue by ItxiaoDz** [ant-tool/atool-build#304]
我是参考[ atool-build 中 less-loader 的 webpack 相关配置](https://github.com/ant-tool/atool-build/blob/a4b3e3eec4ffc09b0e2352d7f9d279c4c28fdb99/src/getWebpackCommonConfig.js#L131-L138) 这个示例来配置的。但是编译时出现错误。
错误信息如下：
```
 Child extract-text-webpack-plugin:
    
    ERROR in ../~/css-loader?sourceMap!../~/postcss/lib/postcss.js!../~/less-loader?{"sourceMap":true,"modifyVars":{"primary-color":"#5BBFAA","table-header-bg":"#EBEFF2","table-row-hover-bg":"#EBEFF2","btn-default-color":"#5BBFAA","btn-default-border":"#5BBFAA"}}!../~/antd/lib/select/style/index.less
    Module build failed: Error: .ant-select {
      box-sizing: border-box;
      .........
   is not a PostCSS plugin
        at Processor.normalize (/Users/chenzhixiang/Documents/projects/fenbiwang/fenbiwang-front-end/node_modules/postcss/lib/processor.js:145:15)
        at new Processor (/Users/chenzhixiang/Documents/projects/fenbiwang/fenbiwang-front-end/node_modules/postcss/lib/processor.js:51:25)
        at Object.postcss (/Users/chenzhixiang/Documents/projects/fenbiwang/fenbiwang-front-end/node_modules/postcss/lib/postcss.js:73:10)
```
package.json的中的依赖如下：
```
 "theme": {
    "primary-color": "#5BBFAA",
    "table-header-bg": "#EBEFF2",
    "table-row-hover-bg": "#EBEFF2",
    "btn-default-color": "#5BBFAA",
    "btn-default-border": "#5BBFAA"
  },

  "devDependencies": {
    "animate.css": "^3.5.1",
    "babel-core": "^6.2.1",
    "babel-loader": "^6.2.0",
    "babel-plugin-antd": "^0.4.0",
    "babel-plugin-transform-runtime": "^6.1.18",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.1.18",
    "babel-runtime": "^6.2.0",
    "css-loader": "^0.23.0",
    "extract-text-webpack-plugin":"1.0.1",
    "fastclick": "^1.0.6",
    "file-loader": "^0.8.5",
    "font-awesome": "^4.6.3",
    "highcharts": "^4.2.5",
    "imports-loader": "^0.6.5",
    "open-browser-webpack-plugin": "0.0.2",
    "node-sass": "^3.4.2",
    "sass-loader": "^3.2.0",
    "style-loader": "^0.13.0",
    "template-html-loader": "0.0.3",
    "url-loader": "^0.5.7",
    "webpack": "~1.12.15",
    "webpack-dev-server": "^1.14.0",
    "whatwg-fetch": "^1.0.0",
    "react-hot-loader": "^1.3.1",
    "redux-devtools": "^3.3.1",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.0.11",
    "moment": "^2.10.0",
    "moment-timezone": "^0.5.0",
    "less":"2.6.1",
    "less-loader":"2.2.3"
  },
  "dependencies": {
    "antd": "2.10.4",
    "html-webpack-plugin": "^2.16.0",
    "react": "^15.0.2",
    "react-dom": "^15.0.2",
    "react-router": "^2.4.1",
    "react-redux": "^4.3.0",
    "react-router-redux": "^4.0.0",
    "redux": "^3.2.1",
    "redux-logger": "^2.6.1",
    "redux-thunk": "^2.1.0"
  }
```
请问这是什么引起的？

**Comment by pigcan** [comment]
theme 的内容需要 `stringify`

**Comment by ItxiaoDz** [comment]
```
loader: ExtractTextPlugin.extract(
            'css?sourceMap!' +
            'postcss!' +
            `less-loader?{"sourceMap":true,"modifyVars":${JSON.stringify(theme)}}`
          ),
        }, {
          test: /\.module\.less$/,
          loader: ExtractTextPlugin.extract(
            'css?sourceMap&modules&localIdentName=[local]___[hash:base64:5]!!' +
            'postcss!' +
            `less-loader?{"sourceMap":true,"modifyVars":${JSON.stringify(theme)}}`
          ),
```

启动编译时，我是这样子写的，应该是有stringify的吧。

**Comment by pigcan** [comment]
检查下是不是少了 postcss-loader

**Comment by ItxiaoDz** [comment]
@pigcan 是的，从google那里找到问题原因了。谢谢了！
