### ISSUE TITLE
支持 i18n，webpackConfig 是数组的情况

### ISSUE THREAD

**Issue by jsenjoy** [ant-tool/atool-build#98]
使用 [i18n-webpack-plugin](https://github.com/webpack/i18n-webpack-plugin) 时，自定义的 webpack.config.js 无法满足要求。

见 https://github.com/webpack/webpack/tree/master/examples/i18n ，要求配置是一个数组，而 atool-build 报错，如下：

```shell
/Users/boom/Workplace/antd/ibops/node_modules/atool-build/lib/build.js:14
  _rimraf2.default.sync(webpackConfig.output.path);
                                            ^

TypeError: Cannot read property 'path' of undefined
    at exports.default (/Users/boom/Workplace/antd/ibops/node_modules/atool-build/lib/build.js:14:45)
    at Object.<anonymous> (/Users/boom/Workplace/antd/ibops/node_modules/atool-build/bin/atool-build:15:24)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by sorrycc** [comment]
https://github.com/webpack/webpack/blob/master/examples/i18n/webpack.config.js
